name: ci

on:
  push:
  pull_request:

jobs:
  linux-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B out/build/linux -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build out/build/linux --parallel
      - name: Test
        run: ctest --test-dir out/build/linux --output-on-failure
